
LEX_SOMA = '+'
LEX_SUB = '-'
LEX_MULT = '*'
LEX_DIV = '/'
LEX_IGUAL = "=="
LEX_DIFERENTE = "!="
LEX_MAIOR = ">"
LEX_MAIORIGUAL = ">="
LEX_MENOR = "<"
LEX_MENORIGUAL = "<="
LEX_ATRIBUICAO = '='

LEX_PONTOVIRGULA = ';'
LEX_VIRGULA = ','
LEX_ABRE_PARENTESES = '('
LEX_FECHA_PARENTESES = ')'
LEX_ABRE_CHAVES = '{'
LEX_FECHA_CHAVES = '}'

LEX_TRUE = 'True'
LEX_FALSE = 'False'